<?php
$ulClass = $this->navigation()->menu()->getUlClass();
$activeClass = $this->navigation()->menu()->getLiActiveClass();

$itemActive = $this->container->getPages();
$html = '';
foreach ($this->container as $item) {
	if ($item->isActive(true) && $item->getPages()) {
		$itemActive = $item->getPages();
		$html .= '<ul class="'.$ulClass.'">' . PHP_EOL;
		$html .= '<li class="'.$activeClass.'">';
		$html .= '<a href="'.$item->getHref().'">' . PHP_EOL .
			($item->get('icon') ? '<span class="icon-'.$item->get('icon').'"></span> ' : '' ) . PHP_EOL .
			$item->getLabel().
		'</a>' . PHP_EOL;
		$html .= '</li>' . PHP_EOL;
		$html .= '</ul>' . PHP_EOL;
		break;
	}
}
echo $html;

$html = '<ul class="'.$ulClass.'">' . PHP_EOL;
foreach ($itemActive as $page):
	if ($this->navigation()->accept($page)):
		$classnames = array();
		if (!empty($page->pages)) { $classnames[] = 'hasSub'; }
		if ($page->isActive(true)) { $classnames[] = $activeClass; }
		
		$html .= '<li class="'.(implode(" ", $classnames)).'">';
		if (!empty($page->pages)) {
			$html .= '<a class="hasSub-toggle" data-toggle="hasSub" href="'.$page->getHref().'">' . PHP_EOL .
			($page->get('icon') ? '<span class="icon-'.$page->get('icon').'"></span> ' : '' ) . PHP_EOL .
			$page->getLabel().
			'</a>' . PHP_EOL;
		} else {
			$html .= '<a href="'.$page->getHref().'">' . PHP_EOL .
			($page->get('icon') ? '<span class="icon-'.$page->get('icon').'"></span> ' : '' ) . PHP_EOL .
			$page->getLabel().
			'</a>' . PHP_EOL;
		}
		if (!empty($page->pages)):
			$html .= '<ul class="hasSub-submenu">' . PHP_EOL;
			foreach ($page->pages as $subpage):
				if ($this->navigation()->accept($subpage)):
					$html .= '<li class="'.($subpage->isActive() ? ''.$this->navigation()->menu()->getLiActiveClass().'' : '').'">' . PHP_EOL;
					$html .= '<a href="'.$subpage->getHref().'">'.$subpage->getLabel().'</a>' . PHP_EOL;
					$html .= '</li>' . PHP_EOL;
				endif;
			endforeach;
			$html .= '</ul>' . PHP_EOL;
		endif;
		
		$html .= '</li>' . PHP_EOL;
	endif;
endforeach;
$html .= '</ul>' . PHP_EOL;
echo $html;