<?php 
$html = '<ul class"'.$this->navigation()->menu()->getUlClass().'">';
foreach ($this->container as $page):
	if ($this->navigation()->accept($page)):
		$classnames = array();
		if (!empty($page->pages)) { $classnames[] = 'dropdown'; }
		if ($page->isActive()) { $classnames[] = $this->navigation()->menu()->getLiActiveClass(); }
		
		$html .= '<li class="'.(implode(" ", $classnames)).'">';
		$html .= '<a href="'.$page->getHref().'">'.$page->getLabel().'</a>';
		
		if (!empty($page->pages))	
			$html .= '<ul class="dropdown-menu">';
			foreach ($page->pages as $subpage):
				if ($this->navigation()->accept($page)):
					$html .= '<li class="'.($subpage->isActive() ? ''.$this->navigation()->menu()->getLiActiveClass().'' : '').'">';
					$html .= '<a href="'.$subpage->getHref().'">'.$subpage->getLabel().'</a>';
					$html .= '</li>';
				endif;
			endforeach;
			$html .= '</ul>	';
		endif;
		
		$html .= '</li>';
	endif;
endforeach;
$html .= '</ul>';

echo $html;