<ul class"<?php echo $this->navigation()->menu()->getUlClass(); ?>">
	<?php foreach ($this->container as $page): ?>
		<?php if ($this->navigation()->accept($page)): ?>
			<li class="<?php echo (!empty($page->pages) ? ' dropdown' : ''); ?><?php echo ($page->isActive() ? ' '.$this->navigation()->menu()->getLiActiveClass().'' : ''); ?>">
				<a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
				<?php if(!empty($page->pages)): ?>		
					<ul class="dropdown-menu">
						<?php foreach ($page->pages as $subpage): ?>
							<li class="<?php echo ($subpage->isActive() ? ''.$this->navigation()->menu()->getLiActiveClass().'' : ''); ?>">
								<a href="<?php echo $subpage->getHref(); ?>"><?php echo $subpage->getLabel(); ?></a>
							</li>
						<?php endforeach; ?>
					</ul>	
				<?php endif; ?>
			</li>
		<?php endif; ?>
	<?php endforeach; ?>
	<?php
    foreach ($this->container as $page) {
        if ($this->navigation()->accept($page)) {
        	echo $this->navigation()->menu()->htmlify($page) . PHP_EOL;
        }
    }
    ?>
</ul>