<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle('[BB] '. $this->translate('MyApplication'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- styles -->
        <?php 
        	$themePath = "assets/themes/taurus/";
        	/* $this->headLink(array(
        			'rel' => 'shortcut icon', 
        			'type' => 'image/vnd.microsoft.icon', 
        			'href' => $this->basePath($themePath . 'img/favicon.ico')
     			))
				->prependStylesheet($this->basePath($themePath . 'css/app.css'))
				->prependStylesheet($this->basePath($themePath . 'css/jquery.gridster.min.css'))
                ->prependStylesheet($this->basePath($themePath . 'js/fancy-box/source/jquery.fancybox.css'))
				->prependStylesheet($this->basePath($themePath . 'css/bootstrap/css/bootstrap-theme.min.css'))
				->prependStylesheet($this->basePath($themePath . 'css/bootstrap/css/bootstrap.min.css'));
			*/
        	$this->headLink(array(
        			'rel' => 'shortcut icon', 
        			'type' => 'image/vnd.microsoft.icon', 
        			'href' => $this->basePath($themePath . 'img/favicon.ico')
     			))
				->prependStylesheet($this->basePath($themePath . 'css/stylesheets.css'));
        	echo $this->headLink();
		?>
        <!-- Scripts -->
        <?php /*
        	$this->headScript()
				->prependFile($this->basePath($themePath . 'js/app.js'))
				->prependFile($this->basePath($themePath . 'js/doubletaptogo.min.js'))
				->prependFile($this->basePath($themePath . 'js/bootstrap/bootstrap.min.js'))
                ->prependFile($this->basePath($themePath . 'js/fancy-box/source/jquery.fancybox.pack.js'))
				->prependFile($this->basePath($themePath . 'js/jquery.gridster.min.js'))
				->prependFile($this->basePath($themePath . 'js/jquery/jquery.min.js'))
				->prependFile($this->basePath($themePath . 'js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
				->prependFile($this->basePath($themePath . 'js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',));

        	echo $this->headScript(); */        	
        ?>
        <?php 
        	$this->headScript()
				->appendFile($this->basePath($themePath . 'js/plugins/jquery/jquery.min.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/jquery/jquery-ui.min.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/jquery/jquery-migrate.min.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/jquery/globalize.js'))    
				->appendFile($this->basePath($themePath . 'js/plugins/bootstrap/bootstrap.min.js'))
 
				->appendFile($this->basePath($themePath . 'js/plugins.js'))    
				->appendFile($this->basePath($themePath . 'js/actions.js')) 

				->appendFile($this->basePath($themePath . 'js/plugins/uniform/jquery.uniform.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/ibutton/jquery.ibutton.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/select2/select2.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/tagsinput/jquery.tagsinput.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/jquery/jquery-ui-timepicker-addon.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/noty/jquery.noty.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/noty/layouts/topCenter.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/noty/layouts/topLeft.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/noty/layouts/topRight.js'))    
				->appendFile($this->basePath($themePath . 'js/plugins/noty/themes/default.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/fancybox/jquery.fancybox.pack.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/knob/jquery.knob.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/flot/jquery.flot.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/flot/jquery.flot.pie.js'))    
				->appendFile($this->basePath($themePath . 'js/plugins/flot/jquery.flot.resize.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/sparkline/jquery.sparkline.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/fullcalendar/fullcalendar.min.js'))

				->appendFile($this->basePath($themePath . "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"))

				->appendFile($this->basePath($themePath . 'js/plugins/datatables/jquery.dataTables.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/shbrush/XRegExp.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/shbrush/shCore.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/shbrush/shBrushXml.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/shbrush/shBrushJScript.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/shbrush/shBrushCss.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/cleditor/jquery.cleditor.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/codemirror/codemirror.js'))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/addon/edit/matchbrackets.js"))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/mode/htmlmixed/htmlmixed.js"))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/mode/xml/xml.js"))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/mode/javascript/javascript.js"))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/mode/css/css.js"))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/mode/clike/clike.js"))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/mode/php/php.js"))

				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.gears.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.silverlight.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.flash.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.browserplus.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.html4.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.html5.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/jquery.plupload.queue/jquery.plupload.queue.js')) 

				->appendFile($this->basePath($themePath . 'js/plugins/elfinder/elfinder.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/filetree/jqueryFileTree.js'))    

				->appendFile($this->basePath($themePath . 'js/plugins/tinymce/tinymce.min.js'))    

				->appendFile($this->basePath($themePath . "js/plugins.js"))
				->appendFile($this->basePath($themePath . "js/actions.js"))

				->appendFile($this->basePath($themePath . "js/charts.js"))
				->appendFile($this->basePath($themePath . "js/maps.js"))
				->appendFile($this->basePath($themePath . "js/settings.js"))
        	;

        	echo $this->headScript();
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath($themePath.'img/zf2-logo.png') ?>" alt="MyApplication" />&nbsp;<?php echo $this->translate('MyApplication') ?></a>
                </div>
				<div class="collapse navbar-collapse">
					<nav>
					    <?php
					    	echo $this->navigation('navigation')
					              ->menu()
					              //->setMinDepth(0)
					              //->setMaxDepth(0)
					              ->setUlClass('nav navbar-nav');
					    ?>
				    </nav>
				</div> 
            </div>
        </nav>
        <div class="container">
            <?php
		    	echo $this->navigation('navigation')
		              ->breadcrumbs()
		              ->setMinDepth(0)
		              ->setPartial('partial/breadcrumb.phtml');
		    
				echo $this->flashMessenger()->render('error', array('error alert flashmessages'));
				echo $this->flashMessenger()->render('warning', array('warning alert flashmessages'));
				echo $this->flashMessenger()->render('success', array('success alert flashmessages'));
				echo $this->flashMessenger()->render('info', array('info alert flashmessages'));
			
				echo $this->content;
			?>
            <hr>
            <footer>
                <p>
                	<span class="copyright">&copy; <?php echo date('Y') ?> by <a href="//dragon-projects.net" target="_blank">[dragon-projects.net]</a> - <?php echo $this->translate('All rights reserved.') ?></span>
                	<span class="poweredby">
                		Powered by &nbsp;
                		<a href="http://php.net" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/php-logo.gif') ?>" height="20" alt="php" /></a> &nbsp;
                		<a href="http://framework.zend.com" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/zf2-logo.png') ?>" height="16" alt="ZendFramework 2" /></a> &nbsp;
                		<a href="http://www.w3.org/html/" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/html5-badge-h-solo.png') ?>" height="16" alt="HTML5" /></a> &nbsp;
                		<a href="http://jquery.com" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/jquery-logo.png') ?>" height="16" alt="jQuery" /></a>
                	</span>
                </p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
