<?php 
	echo $this->doctype(); 
	$oTwitterBootstrap = $this->bootstrap();
?>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<?php echo $this->headTitle('[BB] '. $this->translate($oTwitterBootstrap->AppTitle()))->setSeparator(' - ')->setAutoEscape(false) ?>
		<?php echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>
		<!-- styles -->
		<?php 
			$themePath = "assets/themes/taurus/";
			$this->headLink(array(
					'rel' => 'shortcut icon', 
					'type' => 'image/vnd.microsoft.icon', 
					'href' => $this->basePath($themePath . $oTwitterBootstrap->AppFavicon())
	 			))
				->appendStylesheet($this->basePath($themePath . 'css/stylesheets.css'))
				->appendStylesheet($this->basePath($themePath . 'css/fontawesome/css/font-awesome.min.css'))
			;
			$cssfiles = $oTwitterBootstrap->Config()->get('app')->get('css');
			if (is_array($cssfiles) || ($cssfiles instanceof \Zend\Config\Config)) foreach ($cssfiles as $key => $file) {
				$this->headLink()->appendStylesheet($this->basePath($file));
			}
			echo $this->headLink();
		?>
		<!-- scripts -->
		<?php 
			$this->headScript()
				->appendFile($this->basePath($themePath . 'js/plugins/jquery/jquery.min.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/jquery/jquery-ui.min.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/jquery/jquery-migrate.min.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/jquery/globalize.js'))	
				->appendFile($this->basePath($themePath . 'js/plugins/bootstrap/bootstrap.min.js'))
 
				->appendFile($this->basePath($themePath . 'js/plugins.js'))	
				->appendFile($this->basePath($themePath . 'js/actions.js')) 

				->appendFile($this->basePath($themePath . 'js/plugins/uniform/jquery.uniform.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js'))

				//->appendFile($this->basePath($themePath . 'js/plugins/ibutton/jquery.ibutton.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/select2/select2.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/tagsinput/jquery.tagsinput.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/jquery/jquery-ui-timepicker-addon.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/noty/jquery.noty.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/noty/layouts/topCenter.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/noty/layouts/topLeft.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/noty/layouts/topRight.js'))	
				->appendFile($this->basePath($themePath . 'js/plugins/noty/themes/default.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/fancybox/jquery.fancybox.pack.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/knob/jquery.knob.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/flot/jquery.flot.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/flot/jquery.flot.pie.js'))	
				->appendFile($this->basePath($themePath . 'js/plugins/flot/jquery.flot.resize.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/sparkline/jquery.sparkline.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/fullcalendar/fullcalendar.min.js'))

				->appendFile(("https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"))

				->appendFile($this->basePath($themePath . 'js/plugins/datatables/jquery.dataTables.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/shbrush/XRegExp.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/shbrush/shCore.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/shbrush/shBrushXml.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/shbrush/shBrushJScript.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/shbrush/shBrushCss.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/cleditor/jquery.cleditor.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/codemirror/codemirror.js'))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/addon/edit/matchbrackets.js"))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/mode/htmlmixed/htmlmixed.js"))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/mode/xml/xml.js"))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/mode/javascript/javascript.js"))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/mode/css/css.js"))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/mode/clike/clike.js"))
				->appendFile($this->basePath($themePath . "js/plugins/codemirror/mode/php/php.js"))

				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.gears.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.silverlight.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.flash.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.browserplus.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.html4.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/plupload.html5.js'))
				->appendFile($this->basePath($themePath . 'js/plugins/plupload/jquery.plupload.queue/jquery.plupload.queue.js')) 

				->appendFile($this->basePath($themePath . 'js/plugins/elfinder/elfinder.min.js'))

				->appendFile($this->basePath($themePath . 'js/plugins/filetree/jqueryFileTree.js'))	

				->appendFile($this->basePath($themePath . 'js/plugins/tinymce/tinymce.min.js'))	

				->appendFile($this->basePath($themePath . "js/plugins.js"))
				->appendFile($this->basePath($themePath . "js/actions.js"))

				//->appendFile($this->basePath($themePath . "js/charts.js"))
				//->appendFile($this->basePath($themePath . "js/maps.js"))
				//->appendFile($this->basePath($themePath . "js/settings.js"))
			;
			$jsfiles = $oTwitterBootstrap->Config()->get('app')->get('js');
			if (is_array($jsfiles) || ($jsfiles instanceof \Zend\Config\Config)) foreach ($jsfiles as $key => $file) {
				$this->headScript()->appendFile($this->basePath($file));
			}
				
			echo $this->headScript();
		?>
	</head>
	<body class="no-style" data-settings="close">
		<div class="container">
			<div class="row">					
				<div class="col-md-12">
					<nav class="navbar brb" role="navigation">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-reorder"></span>
							</button>
							<a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath($themePath.$oTwitterBootstrap->AppLogo()) ?>" alt="<?php echo $this->translate($oTwitterBootstrap->AppTitle()) ?>" height="25"/><!-- &nbsp;<?php echo $this->translate($oTwitterBootstrap->AppTitle()) ?> --></a>
						</div>
						<div class="collapse navbar-collapse navbar-ex1-collapse">
							<?php
								$oTwitterBootstrap = $this->bootstrap();
								$oNavBar = $oTwitterBootstrap->Navbar('navigation')
									->setUlClass('nav navbar-nav')
									//->setIconPrefixClass('icon-')
									->setIconPrefixClass('fa fa-')
									->setMinDepth(0)
									->setMaxDepth(2)
									->setDefaultLiClass('')
									->setSubLiClass('')
									->setSubUlClass('dropdown-submenu')
									->setSubUlClassLevel1('dropdown-menu')
									//->setHrefSubToggleOverride('javascript:void(0);')
								;
								echo $oNavBar->render();
							?>
						</div> 
					</nav>
				</div>
			</div>
			
			<div id="panel-breadcrumbs" class="row">					
				<div class="col-md-12">
					<?php 
						$oBreadcrumbs = $oTwitterBootstrap->Breadcrumbs('navigation')
							->setHeader( $this->translate('you are here :') )
							->setMinDepth(0)
						;
						echo $oBreadcrumbs->render(); 
					?>
				</div>
			</div>
			
			<div id="panel-messages" class="row">					
				<div class="col-md-12">		
					<?php
						echo $this->flashMessenger()->render('error', array('error alert flashmessages'));
						echo $this->flashMessenger()->render('warning', array('warning alert flashmessages'));
						echo $this->flashMessenger()->render('success', array('success alert flashmessages'));
						echo $this->flashMessenger()->render('info', array('info alert flashmessages'));
					?>
				</div>
			</div>
			
			<div id="panel-page" class="page-container"><!-- page container -->
			
				<div class="row">
							
					<div class="col-md-2">
						<div class="block block-drop-shadow"><!-- side bar -->
							
							<?php if ($this->zfcUserIdentity()) { ?>
							<div class="user bg-default bg-light-rtl">
								<div class="info">																				
									<span href="#" class="informer informer-three">
										<span>date:</span>
										<?php echo date("Y-m-d"); ?>
									</span>							
									<span href="#" class="informer informer-four">
										<span>user:</span>
										<?php echo $this->zfcUserDisplayName() ?>
									</span>														
									<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(), null, array('class' => "img-circle img-thumbnail")); ?>
								</div>
							</div>
							<?php } ?>					
							<div class="content">
								<!-- place for navigation -->
								<?php
								$ulClass = 'nav';
								$activeClass = $oTwitterBootstrap->Navbar()->getLiActiveClass();
								
								$container = $oTwitterBootstrap->Navbar('navigation')->getContainer(); // $this->navigation()->menu()->getContainer(); // 
								$itemActive = $container; //->getPages();
								$html = '';
								foreach ($container->getPages() as $item) {
									if ($item->isActive(true) && $item->getPages()) {
										$itemActive = $item; //->getPages();
										$html .= '<ul class="'.$ulClass.'">' . PHP_EOL;
										$html .= '    <li class="'.$activeClass.'">';
										$html .= '        <a href="'.$item->getHref().'">' . PHP_EOL .
											($item->get('icon') ? '            <span class="icon-'.$item->get('icon').'"></span> ' : '' ) . PHP_EOL .
											$item->getLabel().
										'        </a>' . PHP_EOL;
										$html .= '    </li>' . PHP_EOL;
										$html .= '</ul>' . PHP_EOL;
										break;
									}
								}
								echo $html;
								
								$oNavBar = $oTwitterBootstrap->Navbar($itemActive)
									->setUlClass('page-navigation')
									->setIconPrefixClass('icon-')
									->setMinDepth(0)
									->setMaxDepth(1)
									//->setOnlyActiveBranch()
									->setUlClass('nav')
									->setSubUlClass('')
									->setSubUlClassLevel1('')
									->setDefaultLiClass('')
									->setSubLiClass('')
									->setSubLiClassLevel0('')
									->setLiActiveClass('active')
								;
								echo $oNavBar->render();
								?>
							</div>
						</div>
					</div>
					
					<div class="col-md-10">
					
						<div class="content">
							<?php
								echo $this->content;
							?>
						</div>
						<div class="footer">
							<footer>
								<p>
									<span class="copyright pull-left">&copy; <?php echo date('Y') ?> by <a href="//dragon-projects.net" target="_blank">[dragon-projects.net]</a> - <?php echo $this->translate('All rights reserved.') ?></span>
									<span class="poweredby pull-right">
										<?php echo $this->translate('Powered by') ?> &nbsp;
										<a href="http://php.net" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/php-logo.gif') ?>" height="20" alt="php" /></a> &nbsp;
										<a href="http://framework.zend.com" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/zf2-logo.png') ?>" height="16" alt="ZendFramework 2" /></a> &nbsp;
										<a href="http://www.w3.org/html/" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/html5-badge-h-solo.png') ?>" height="16" alt="HTML5" /></a> &nbsp;
										<a href="http://jquery.com" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/jquery-logo.png') ?>" height="16" alt="jQuery" /></a>
									</span>
								</p>
							</footer>
						</div>
						
					</div>
					
				</div>
			</div> <!-- /page-container -->
			
		</div> <!-- /container -->
		<?php echo $this->inlineScript() ?>
	</body>
</html>
